### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Crusher6581** [1MaddieX/LyricMateBot#1]
**Describe the bug**
Lyricmate isn't playing queued songs, only the first song inputted with the !play command. Lyricmate played the first song I queued, and stated "Queue finished!" and didn't play the others.
**To Reproduce**
Ex:
1. Send '!play' command
2. Wait for 'more than one song to be queued'
3. Try to listen

**Expected behavior**
Expected for all songs in the queue to be played without manual intervention.
**Screenshots**
Please add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/28161703/85816130-6cd26200-b738-11ea-8046-063fcd5f2ea6.png)

**If On Desktop (please complete the following information):**
 - OS: Windows 10
 - Client Type: Desktop
 - Version 0.4-1

**I DO NOT OFFER SUPPORT FOR THIRD PARTY CLIENTS**

**If On Mobile (please complete the following information):**
 - OS: [e.g. iOS 13.3]
 - Client Version [e.g. 21.0 Stable]

**Additional context**
Was queuing a bunch of lizzo songs lmao

**Comment by cl0vrfi3ld** [comment]
Hey, I'm really sorry bout this! It's prolly something to do with the new update, I believe I have found the issue and am working on it now! Thanks for reporting this!

**Comment by cl0vrfi3ld** [comment]
Hey, your issue should be resolved (with version 0.4-2), if it's not, please open another issue!
